## Section 1: Pattern Matching and Replacement

### Example 1: Basic Substitution with `sub()`

In [46]:
y <- "Number of participants: 25"
result <- sub("25", "30", y)
print(result)

[1] "Number of participants: 30"

### Example 2: First-Occurrence Limitation of `sub()`

In [47]:
y <- "Mr. Singh is the smart one. Mr. Singh is funny, too."
print(y)
result <- sub("Mr. Singh", "Professor Jha", y)
print(result)

[1] "Mr. Singh is the smart one. Mr. Singh is funny, too."
[1] "Professor Jha is the smart one. Mr. Singh is funny, too."

### Example 3: Global Substitution with `gsub()`

In [48]:
y <- "Mr. Singh is the smart one. Mr. Singh is funny, too."
result <- gsub("Mr. Singh", "Professor Jha", y)
print(result)

[1] "Professor Jha is the smart one. Professor Jha is funny, too."

### Comparison of `sub()` and `gsub()` behavior

In [49]:
sub("Mr. Singh", "Professor Jha", y)
gsub("Mr. Singh", "Professor Jha", y)

[1] "Professor Jha is the smart one. Mr. Singh is funny, too."

[1] "Professor Jha is the smart one. Professor Jha is funny, too."

### Example 4: Value Extraction using `grep()`

In [50]:
str <- c(
  "R Course",
  "exercises",
  "include examples of R language"
)
result <- grep("ex", str, value = TRUE)
print(result)

[1] "exercises"                      "include examples of R language"

### Example 5: Finding Indices with `grep()`

In [51]:
str <- c(
  "R Course",
  "exercises",
  "include examples of R language"
)
result <- grep("ex", str, value = FALSE)
print(result)

[1] 2 3

### Example 6: Case-Insensitive Matching with `grep()`

In [52]:
str <- c(
  "R Course",
  "exercises",
  "include examples of r language",
  "in R software."
)
result1 <- grep(
  "R",
  str,
  ignore.case = FALSE,
  value = TRUE
)
print(result1)
result2 <- grep(
  "R",
  str,
  ignore.case = TRUE,
  value = TRUE
)
print(result2)

[1] "R Course"       "in R software."
[1] "R Course"                       "exercises"
[3] "include examples of r language" "in R software."

### Example 7: Index Retrieval & Case Sensitivity Options

In [53]:
str <- c(
  "R Course",
  "exercises",
  "include examples of r language",
  "in R software."
)
grep(
  "R",
  str,
  ignore.case = TRUE,
  value = FALSE
)
grep(
  "R",
  str,
  ignore.case = FALSE,
  value = FALSE
)

[1] 1 2 3 4

[1] 1 4

### Example 8: Searching within Vector Constructs

In [54]:
x <- "R course 24.07.2021"
y <- "Number of participants: 25"
combined <- c(x, y)
print(combined)
result <- grep("our", combined)
print(result)

[1] "R course 24.07.2021"        "Number of participants: 25"
[1] 1

### Example 9: Matching Target Prefix "Num"

In [55]:
x <- "R course 24.07.2022"
y <- "Number of participants: 50"
combined <- c(x, y)
print(combined)
result <- grep("Num", combined)
print(result)

[1] "R course 24.07.2022"        "Number of participants: 50"
[1] 2

### Example 10: Logical Vector Creation via `grepl()`

In [56]:
str <- c(
  "R Course",
  "exercises",
  "include examples of R language"
)
result <- grepl("R", str)
print(result)

[1]  TRUE FALSE  TRUE

### Example 11: Boolean Checks for Specific Patterns

In [57]:
str <- c(
  "R Course",
  "exercises",
  "include examples of R language"
)
result <- grepl("ex", str)
print(result)

[1] FALSE  TRUE  TRUE

## Section 2: Exploration of Datasets

### Example 12: Loading the Painters Dataset

In [58]:
library(MASS)
painters

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A
F. Zucarro      10          13       8      8         B
Fr. Salviata    13          15       8      8         B
Parmigiano      10          15       6      6         B
Primaticcio     15          14       7     10         B
T. Zucarro      13          14      10      9         B
Volterra        12          15       5      8         B
Barocci         14          15       6     10         C
Cortona         16          14      12      6         C
Josepin         10          10       6      2         C
L. Jordaens     13          12       9      6         C
Testa           11          15       0      6         C
Vanius          15          15      12     13         C
Bassano          6           8      17      0         D
Bellini          4           6      14      0         D
Giorgione        8           9      18      4         D
Murillo          6           8      15      4         D
Palma Giovane   12           9      14      6         D
Palma Vecchio    5           6      16      0         D
Pordenone        8          14      17      5         D
Tintoretto      15          14      16      4         D
Titian          12          15      18      6         D
Veronese        15          10      16      3         D
Albani          14          14      10      6         E
Caravaggio       6           6      16      0         E
Corregio        13          13      15     12         E
Domenichino     15          17       9     17         E
Guercino        18          10      10      4         E
Lanfranco       14          13      10      5         E
The Carraci     15          17      13     13         E
Durer            8          10      10      8         F
Holbein          9          10      16     13         F
Pourbus          4          15       6      6         F
Van Leyden       8           6       6      4         F
Diepenbeck      11          10      14      6         G
J. Jordaens     10           8      16      6         G
Otho Venius     13          14      10     10         G
Rembrandt       15           6      17     12         G
Rubens          18          13      17     17         G
Teniers         15          12      13      6         G
Van Dyck        15          10      17     13         G
Bourdon         10           8       8      4         H
Le Brun         16          16       8     16         H
Le Suer         15          15       4     15         H
Poussin         15          17       6     15         H

### Example 13: Dataset Preview

In [59]:
head(painters)

              Composition Drawing Colour Expression School
Da Udine      10           8      16      3         A
Da Vinci      15          16       4     14         A
Del Piombo     8          13      16      7         A
Del Sarto     12          16       9      8         A
Fr. Penni      0          15       8      0         A
Guilio Romano 15          16       4     14         A

### Example 14: Numeric Data Verification

In [60]:
is.numeric(painters$School)
is.numeric(painters$Drawing)

[1] FALSE

[1] TRUE

### Example 15: Factor Data Verification

In [61]:
is.factor(painters$School)
is.factor(painters$Drawing)

[1] TRUE

[1] FALSE

### Example 16: Column Names Analysis

In [62]:
colnames(painters)

[1] "Composition" "Drawing"     "Colour"      "Expression"  "School"

### Example 17: Comprehensive Summary Statistics

In [63]:
summary(painters)

  Composition       Drawing          Colour        Expression         School
 Min.   : 0.00   Min.   : 6.00   Min.   : 0.00   Min.   : 0.000   A      :10
 1st Qu.: 8.25   1st Qu.:10.00   1st Qu.: 7.25   1st Qu.: 4.000   D      :10
 Median :12.50   Median :13.50   Median :10.00   Median : 6.000   E      : 7
 Mean   :11.56   Mean   :12.46   Mean   :10.94   Mean   : 7.667   G      : 7
 3rd Qu.:15.00   3rd Qu.:15.00   3rd Qu.:16.00   3rd Qu.:11.500   B      : 6
 Max.   :18.00   Max.   :18.00   Max.   :18.00   Max.   :18.000   C      : 6
                                                                  (Other): 8

### Example 18: Individual Categorical Summary

In [64]:
summary(painters$School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

### Example 19: Environment Binding with `attach()`

In [65]:
attach(painters)
summary(School)
summary(Composition)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

### Example 20: Direct Summaries of Attached Attributes

In [66]:
summary(School)
summary(Composition)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

### Example 21: Unbinding Environment with `detach()`

In [67]:
detach(painters)
summary(School)

ERROR: Error: object 'School' not found

### Example 22: Safe Accessing After Detachment

In [68]:
summary(painters$School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

### Example 23: Data Filtering using `subset()`

In [69]:
subset(
  painters,
  School == "F"
)

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

### Example 24: Direct Logical Bracketing

In [70]:
painters[
  painters[["School"]] == "F",
]

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

### Example 25: Generic Indexing Template

In [71]:
dataframe[ROWS, COLUMNS]

ERROR: Error: object 'dataframe' not found

### Example 26: Practical Application of Bracket Filter

In [72]:
painters[condition, ]

ERROR: Error: object 'condition' not found

### Example 27: Relational Operations on Subset Selection

In [73]:
subset(
  painters,
  Composition <= 6
)

              Composition Drawing Colour Expression School
Fr. Penni     0           15       8     0          A
Perugino      4           12      10     4          A
Bassano       6            8      17     0          D
Bellini       4            6      14     0          D
Murillo       6            8      15     4          D
Palma Vecchio 5            6      16     0          D
Caravaggio    6            6      16     0          E
Pourbus       4           15       6     6          F

### Example 28: Column Exclusion within Subsets

In [74]:
subset(
  painters,
  School == "F",
  select = c(-3, -5)
)

           Composition Drawing Expression
Durer      8           10       8
Holbein    9           10      13
Pourbus    4           15       6
Van Leyden 8            6       4

### Example 29: Splitting Datasets by Factors

In [75]:
splitted <- split(
  painters,
  painters$School
)
splitted

$A
                Composition Drawing Colour Expression School
Da Udine                 10       8     16          3      A
Da Vinci                 15      16      4         14      A
Del Piombo                8      13     16          7      A
Del Sarto                12      16      9          8      A
Fr. Penni                 0      15      8          0      A
Guilio Romano            15      16      4         14      A
Michelangelo              8      17      4          8      A
Perino del Vaga          15      16      7          6      A
Perugino                  4      12     10          4      A
Raphael                  17      18     12         18      A

$B
             Composition Drawing Colour Expression School
F. Zucarro            10      13      8          8      B
Fr. Salviata          13      15      8          8      B
Parmigiano            10      15      6          6      B
Primaticcio           15      14      7         10      B
T. Zucarro            13      14     10          9      B
Volterra              12      15      5          8      B

$C
            Composition Drawing Colour Expression School
Barocci              14      15      6         10      C
Cortona              16      14     12          6      C
Josepin              10      10      6          2      C
L. Jordaens          13      12      9          6      C
Testa                11      15      0          6      C
Vanius               15      15     12         13      C

$D
              Composition Drawing Colour Expression School
Bassano                 6       8     17          0      D
Bellini                 4       6     14          0      D
Giorgione               8       9     18          4      D
Murillo                 6       8     15          4      D
Palma Giovane          12       9     14          6      D
Palma Vecchio           5       6     16          0      D
Pordenone               8      14     17          5      D
Tintoretto             15      14     16          4      D
Titian                 12      15     18          6      D
Veronese               15      10     16          3      D

$E
            Composition Drawing Colour Expression School
Albani               14      14     10          6      E
Caravaggio            6       6     16          0      E
Corregio             13      13     15         12      E
Domenichino          15      17      9         17      E
Guercino             18      10     10          4      E
Lanfranco            14      13     10          5      E
The Carraci          15      17     13         13      E

$F
           Composition Drawing Colour Expression School
Durer                8      10     10          8      F
Holbein              9      10     16         13      F
Pourbus              4      15      6          6      F
Van Leyden           8       6      6          4      F

$G
            Composition Drawing Colour Expression School
Diepenbeck           11      10     14          6      G
J. Jordaens          10       8     16          6      G
Otho Venius          13      14     10         10      G
Rembrandt            15       6     17         12      G
Rubens               18      13     17         17      G
Teniers              15      12     13          6      G
Van Dyck             15      10     17         13      G

$H
        Composition Drawing Colour Expression School
Bourdon          10       8      8          4      H
Le Brun          16      16      8         16      H
Le Suer          15      15      4         15      H
Poussin          15      17      6         15      H

### Example 30: Retrieving Split Groups

In [76]:
splitted$A

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A

### Example 31: Group F Subset

In [77]:
splitted$F

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

### Example 32: Group H Subset

In [78]:
splitted$H

        Composition Drawing Colour Expression School
Bourdon 10           8      8       4         H
Le Brun 16          16      8      16         H
Le Suer 15          15      4      15         H
Poussin 15          17      6      15         H

### Example 33: Type Assessment of Splits

In [79]:
is.data.frame(splitted$A)

[1] TRUE

## Section 3: Data Frame Operations

### Example 34: Data Frame 1 Initialization

In [80]:
df1 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  popnsize = c(1000, 2000, 3000, 4000)
)
df1

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

### Example 35: Data Frame 2 Initialization

In [81]:
df2 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  samplesize = c(100, 200, 300, 400),
  surveycompleted = c("Yes", "No", "Yes", "No")
)
df2

  state samplesize surveycompleted
1 UP    100        Yes
2 MP    200        No
3 AP    300        Yes
4 JK    400        No

### Example 36: Column Binding with `cbind()`

In [82]:
result <- cbind(df1, df2)
print(result)

  state popnsize state samplesize surveycompleted
1    UP     1000    UP        100             Yes
2    MP     2000    MP        200              No
3    AP     3000    AP        300             Yes
4    JK     4000    JK        400              No

### Example 37: Relational Merging via Keys

In [83]:
result <- merge(
  df1,
  df2,
  by = "state"
)
print(result)

  state popnsize samplesize surveycompleted
1    AP     3000        300             Yes
2    JK     4000        400              No
3    MP     2000        200              No
4    UP     1000        100             Yes

### Example 38: Configuration of Join Parameters

In [84]:
by = "state"

### Example 39: Specified Parameter Matching in Merge

In [85]:
merged_data <- merge(
  x = df1,
  y = df2,
  by = "state"
)
merged_data

  state popnsize samplesize surveycompleted
1 AP    3000     300        Yes
2 JK    4000     400        No
3 MP    2000     200        No
4 UP    1000     100        Yes

### Example 40: Target Data Frame Primary Preparation

In [86]:
df11 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  popnsize = c(1000, 2000, 3000, 4000)
)
df11

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

### Example 41: Target Data Frame Secondary Preparation

In [87]:
df22 <- data.frame(
  state = c("Bihar", "Delhi", "Punjab"),
  popnsize = c(100, 200, 300)
)
df22

  state  popnsize
1 Bihar  100
2 Delhi  200
3 Punjab 300

### Example 42: Row Binding with `rbind()`

In [88]:
result <- rbind(
  df11,
  df22
)
print(result)

   state popnsize
1     UP     1000
2     MP     2000
3     AP     3000
4     JK     4000
5  Bihar      100
6  Delhi      200
7 Punjab      300