# R Matrix Operations

NPTEL Week 4.

## Matrix Creation
### Basic Matrix

In [ ]:
x <- matrix(nrow = 4, ncol = 3, data = 1:12)

x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

### Naming Rows and Columns

In [ ]:
x <- matrix(nrow = 4, ncol = 3, data = 1:12)

rownames(x) <- c("r1", "r2", "r3", "r4")
colnames(x) <- c("c1", "c2", "c3")

x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

### Matrix with Constant Values

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 2)

x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

### Another Matrix with Constant Values

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 2)

x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

### Diagonal Matrix

In [ ]:
d <- diag(5, nrow = 3, ncol = 3)

d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

### Matrix Created Row-wise

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

## Matrix Properties and Basic Functions
### Transposing a Matrix

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

xt <- t(x)

xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

### Row and Column Sums

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8)

x

rowSums(x)
colSums(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

[1] 10 26

### Row and Column Means

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8)

x

rowMeans(x)
colMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 3 4 5 6

[1] 2.5 6.5

### Another Example of Row and Column Means

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8)

x

rowMeans(x)
colMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 3 4 5 6

[1] 2.5 6.5

## Matrix Subsetting
### Selecting a Row

In [ ]:
x <- matrix(nrow = 5, ncol = 3, byrow = TRUE, data = 1:15)

x[3, ]

[1] 7 8 9

### Selecting a Column

In [ ]:
x <- matrix(nrow = 5, ncol = 3, byrow = TRUE, data = 1:15)

x[, 2]

[1]  2  5  8 11 14

### Selecting a Range of Rows and Columns

In [ ]:
x <- matrix(nrow = 5, ncol = 3, byrow = TRUE, data = 1:15)

x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

### Selecting Specific Rows and Columns

In [ ]:
x <- matrix(nrow = 5, ncol = 3, byrow = TRUE, data = 1:15)

x[c(1, 4), c(1, 3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

### Another Example of Selecting Specific Rows and Columns

In [ ]:
x <- matrix(nrow = 5, ncol = 3, byrow = TRUE, data = 1:15)

x[c(1, 4), c(1, 3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

## Scalar Operations on Matrices
### Subtraction by a Scalar

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

x - 5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

### Multiplication by a Scalar

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

5 * x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

### Division by a Scalar

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

x / 2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

## Matrix Arithmetic
### Displaying Two Matrices

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

y <- matrix(nrow = 4, ncol = 2, data = 11:18, byrow = TRUE)

x
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

### Matrix Addition

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

y <- matrix(nrow = 4, ncol = 2, data = 11:18, byrow = TRUE)

x + y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

### Matrix Subtraction

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

y <- matrix(nrow = 4, ncol = 2, data = 11:18, byrow = TRUE)

x - y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

### Scalar Multiplication (Revisited)

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

4 * x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

### Combined Scalar and Matrix Addition

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

x + 4 * x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

### Combined Scalar and Matrix Subtraction

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

4 * x - x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

## Matrix Multiplication
### Displaying Matrices with Different Dimensions

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

y <- matrix(nrow = 2, ncol = 4, data = 11:18, byrow = TRUE)

x
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

### Matrix Multiplication (X %*% Y)

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

y <- matrix(nrow = 2, ncol = 4, data = 11:18, byrow = TRUE)

x %*% y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

### Matrix Multiplication (Y %*% X)

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

y <- matrix(nrow = 2, ncol = 4, data = 11:18, byrow = TRUE)

y %*% x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

### Transpose and Matrix Multiplication (X'X)

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

### Matrix Multiplication and Transpose (XX')

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

### Crossproduct of a Matrix

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)

crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

## Advanced Matrix Functions
### Matrix Inverse (solve function)

In [ ]:
y <- matrix(
  nrow = 2,
  ncol = 2,
  byrow = TRUE,
  data = c(84, 100, 100, 120)
)

y

solve(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

### Eigenvalues and Eigenvectors

In [ ]:
y <- matrix(
  nrow = 2,
  ncol = 2,
  byrow = TRUE,
  data = c(84, 100, 100, 120)
)

eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

## Combining Matrices
### Row Binding Matrices (rbind)

In [ ]:
x <- matrix(nrow = 3, ncol = 2, data = 1:6, byrow = TRUE)

y <- matrix(nrow = 3, ncol = 2, data = 11:16, byrow = TRUE)

rbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

### Column Binding Matrices (cbind)

In [ ]:
x <- matrix(nrow = 3, ncol = 2, data = 1:6, byrow = TRUE)

y <- matrix(nrow = 3, ncol = 2, data = 11:16, byrow = TRUE)

cbind(x, y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

### Another Example of Column Binding Matrices

In [ ]:
x <- matrix(nrow = 3, ncol = 2, data = 1:6, byrow = TRUE)

y <- matrix(nrow = 3, ncol = 2, data = 11:16, byrow = TRUE)

cbind(x, y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

## Logical Operators
### Basic Logical Operations (AND, OR, NOT)

In [ ]:
x <- TRUE
y <- FALSE

x & y
x | y
!x

[1] FALSE

[1] TRUE

[1] FALSE

### Short-Circuiting OR (||)

In [ ]:
x <- 8

(x < 10) || (x < 2)

x <- 18

(x < 10) || (x < 2)

[1] TRUE

[1] FALSE

### Element-wise OR (|) with Vectors

In [ ]:
x <- c(8, 18)

x1 <- 8

(x1 < 10) || (x1 < 2)

(x < 10) | (x < 2)

[1] TRUE

[1]  TRUE FALSE

### Short-Circuiting AND (&&) vs. Element-wise AND (&)

In [ ]:
x <- c(8, 18)

# && is used with a single value
x1 <- 8

(x1 < 10) && (x1 > 2)

# & is used element-by-element with a vector
(x < 10) & (x > 2)

[1] TRUE

[1]  TRUE FALSE

### Using Logical Operators for Subsetting (AND)

In [ ]:
x <- 1:6

# Check which values satisfy both conditions
(x > 2) & (x < 5)

# Select only those values
x[(x > 2) & (x < 5)]

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

### Using Logical Operators for Subsetting (OR)

In [ ]:
x <- 1:6

# Check which values satisfy either condition
(x > 2) | (x < 5)

# Select those values
x[(x > 2) | (x < 5)]

[1] TRUE TRUE TRUE TRUE TRUE TRUE

[1] 1 2 3 4 5 6

### Exclusive OR (xor)

In [ ]:
x <- TRUE
y <- FALSE

xor(x, y)

[1] TRUE

### Checking Truth Values (isTRUE, isFALSE)

In [ ]:
isTRUE(8 < 6)

isTRUE(8 > 6)

isFALSE(5 < 8)

isFALSE(5 > 8)

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

## Comparison Operators
### Greater Than, Less Than, Greater Than or Equal To, Less Than or Equal To

In [ ]:
8 > 7

7 < 5

7 > 7

7 >= 7

8 < 8

8 <= 8

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

### Inequality and Equality Operators

In [ ]:
8 != 9

9 != 9

7 == 7

7 == 8

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

### Simple Logical NOT (!)

In [ ]:
x <- TRUE

!x

[1] FALSE

### Element-wise Comparison with Vectors

In [ ]:
x <- c(1, 2, 3)
y <- c(4, 5, 6)

x > y

x < y

x != y

x == y

[1] FALSE FALSE FALSE

[1] TRUE TRUE TRUE

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

## Logical Variables
### Creating Logical Variables

In [ ]:
x <- 5

Logical1 <- (x > 2)
Logical1
is.logical(Logical1)

Logical2 <- (x < 10)
Logical2
is.logical(Logical2)

Logical3 <- (x != 5)
Logical3
is.logical(Logical3)

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

### Further Examples of Logical Variables

In [ ]:
x <- 5

Logical4 <- (2 * x > 11)
Logical4
is.logical(Logical4)

Logical5 <- (3 * x < 20)
Logical5
is.logical(Logical5)

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE